name: execution

on:
  workflow_dispatch: # This enables the "Run workflow" button
    inputs:
      env_type:
        description: 'Select Environment'
        required: true
        default: 'perf'
        type: choice
        options:
          - dev
          - qa
          - perf
      test_type:
        description: 'Select Test Type'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - load
          - stress
          - vu1d5m

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup K6
        uses: grafana/setup-k6-action@v1.1.0
        
# 4. RUN k6 (This is where filename and flags go)
      - name: Execute k6 Test
        env:
          K6_WEB_DASHBOARD: true
          K6_WEB_DASHBOARD_PORT: 5665
          K6_WEB_DASHBOARD_HOST: 0.0.0.0
          K6_WEB_DASHBOARD_EXPORT: report.html
        run: |
          k6 run ./test_scripts/End_to_End_All_Methods.js \
            --env env=${{ inputs.env_type }} \
            --env TEST_TYPE=${{ inputs.test_type }}
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: End_to_End_All_Methods.html
